/**
 * Adds the developer watermark to the social share cards.
 *
 * The base 1200x630 OG card (public/og.png, generated by make-icons.mjs) gets a
 * small "by Arun Neupane" credit in the bottom-right corner, then the same card
 * is written out for every article's `public/og/<slug>.png`.
 *
 * Run after `node scripts/make-icons.mjs`:
 *   node scripts/make-icons.mjs && node scripts/make-og.mjs
 */

import { chromium } from "playwright";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const PUBLIC = join(ROOT, "public");
const BASE = join(PUBLIC, "og.png");
const OG_DIR = join(PUBLIC, "og");
const W = 1200;
const H = 630;

const SLUGS = [
  "zen-mode",
  "speedrun-minesweeper-records",
  "rush-mode-guide-and-tips",
  "practice-mode-and-smart-hints",
  "play-minesweeper-on-mobile",
  "no-guess-mode",
  "minesweeper-strategy-for-beginners",
  "minesweeper-speed-techniques",
  "minesweeper-probability-and-guessing",
  "minesweeper-number-patterns",
  "minesweeper-glossary",
  "minesweeper-3bv-and-good-times",
  "how-to-play-minesweeper",
  "daily-minesweeper-challenge",
  "custom-minesweeper-boards",
  "brief-history-of-minesweeper",
];

const base = await readFile(BASE);

const html = `
<!doctype html>
<html>
  <body style="margin:0">
    <img id="card" src="data:image/png;base64,${base.toString("base64")}"
         alt="" width="${W}" height="${H}"
         style="position:absolute;inset:0;width:${W}px;height:${H}px;object-fit:cover" />
    <div style="position:absolute;bottom:24px;right:32px;
                font-family:'Segoe UI','SF Pro Text',system-ui,-apple-system,sans-serif;
                font-size:19px;font-weight:600;letter-spacing:0.4px;color:rgba(250,250,252,0.62)">
      by Arun Neupane
    </div>
  </body>
</html>`;

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: W, height: H } });
await page.setContent(html, { waitUntil: "load" });
await page.$eval("#card", (img) => img.decode());
await page.waitForTimeout(120);

const out = await page.screenshot({ path: BASE, type: "png" });
console.log(`wrote public/og.png (${out.length} bytes)`);

await mkdir(OG_DIR, { recursive: true });
for (const slug of SLUGS) {
  const dest = join(OG_DIR, `${slug}.png`);
  await copyFile(BASE, dest);
  console.log(`wrote public/og/${slug}.png`);
}

await browser.close();
console.log("done");